force-app/main/default/objects/outfunds__Funding_Program__c/fields/ApplicationForm__c.field-meta.xml
<CustomField>
    <fullName>ApplicationForm__c</fullName>
    <description>List of flows that can be selected to launch a new application (Funding Request) from a Funding Program.</description>
    <inlineHelpText>Select a flow to use when creating a new application (Funding Request) for this Funding Program.</inlineHelpText>
    <label>Application Form</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>OutboundFundsCreateApplication</fullName>
                <label>Create Application</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/controllers/FundingProgramApplyButtonController.cls
public with sharing class FundingProgramApplyButtonController {
    /**
     * @description Retrieve Application form's API Name
     * @return      String
     */
    @AuraEnabled(cacheable=true)
    public static String getFundingProgramApplicationFormApiName() {
        if (!Schema.SObjectType.outfunds__Funding_Program__c.isAccessible()) {
            System.AuraHandledException auraHandledException = new AuraHandledException(
                System.Label.Does_Not_Have_Read_Access_For_Object_Message
            );
            auraHandledException.setMessage(
                System.Label.Does_Not_Have_Read_Access_For_Object_Message
            );
            throw auraHandledException;
        }
        if (
            !Schema.SObjectType.outfunds__Funding_Program__c.fields.ApplicationForm__c.isAccessible()
        ) {
            System.AuraHandledException auraHandledException = new AuraHandledException(
                System.Label.Does_Not_Have_Read_FLS_Access_Message
            );
            auraHandledException.setMessage(
                System.Label.Does_Not_Have_Read_FLS_Access_Message
            );
            throw auraHandledException;
        }

        return Schema.SObjectType.outfunds__Funding_Program__c.fields.ApplicationForm__c.getName();
    }
}